# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graffy_rn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for graffy_rn
  pod 'Google/SignIn'

  target 'graffy_rnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
